name: Airflow_CI
on:
  push:
     branches: [main]
  pull_request:
     branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: List all files
        run: ls

      - name: Install Python
        uses: actions/setup-python@v5
        with:
           python-version: '3.10' 
      - run: python .env_/run_ci_date.py


      - name: List all files
        run: ls


        

